name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake (GIF with black background)
        uses: Platane/snk@v3
        with:
          github_user_name: gizembm
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.gif
          color_snake: "#b084f5"
          color_dots: "#222,#444,#666,#888,#aaa"
          background: "#000000"

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
