name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır
  workflow_dispatch:       # Manuel olarak Actions sekmesinden çalıştırabilirsin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: gizembm
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
