name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır
  workflow_dispatch:        # Manuel çalıştırmaya da izin verir

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake (dark theme GIF only)
        uses: Platane/snk@v3
        with:
          github_user_name: gizembm
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          color_snake: "#b084f5"
          color_dots: "#222,#444,#666,#888,#aaa"
          background_color: "#000000"
          
      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
